spring:
  application:
    name: activiti-db
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  activiti:
    database-schema-update: true
server:
  port: 8885

info:
  app:
    name: activiti-db
    version: v1.0.0



